import Link from "next/link";

import { requireStudentPage } from "@/lib/access";
import { getStudentJourneyOverview } from "@/lib/studentJourney";

export const dynamic = "force-dynamic";

function formatDate(value: Date) { return new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "long", year: "numeric", timeZone: "Europe/Moscow" }).format(value); }

export default async function StudentRoutePage() {
  const user = await requireStudentPage();
  const journey = await getStudentJourneyOverview(user.id);
  if (!journey.profile || !journey.roadmap) return <main className="min-h-screen bg-[#f3f7fa] px-4 py-8"><div className="mx-auto max-w-3xl rounded-[32px] bg-white p-8"><h1 className="text-3xl font-black">Маршрут ещё не построен</h1><p className="mt-3 text-slate-600">Заполните параметры подготовки и завершите входную диагностику.</p><Link href={journey.profile ? "/student/diagnostic" : "/student/start"} className="mt-6 inline-flex rounded-xl bg-cyan-700 px-5 py-3 text-sm font-black text-white">Продолжить старт →</Link></div></main>;

  return <main className="min-h-screen bg-[#f3f7fa] px-4 py-6 text-[#102638] sm:px-6"><div className="mx-auto max-w-5xl"><Link href="/student" className="text-sm font-bold text-cyan-700">← В кабинет</Link><header className="mt-4 rounded-[32px] bg-[#092535] p-7 text-white sm:p-10"><div className="font-mono text-[11px] uppercase tracking-[0.18em] text-cyan-300">global.route</div><h1 className="mt-3 text-3xl font-black sm:text-5xl">Маршрут до {journey.profile.targetScore}+ баллов</h1><p className="mt-4 text-sm text-slate-300">До {formatDate(journey.profile.examDate)} · {Math.round(journey.profile.weeklyMinutes / 60)} ч в неделю · маршрут учитывает диагностику и зависимости тем.</p><div className="mt-5 flex gap-3"><Link href="/student/calendar" className="rounded-xl bg-white px-4 py-2.5 text-sm font-black text-slate-950">Открыть календарь</Link><Link href="/student/skills" className="rounded-xl border border-white/20 px-4 py-2.5 text-sm font-black text-white">Карта навыков</Link></div></header><section className="mt-6 space-y-3">{journey.roadmap.milestones.map((milestone, index) => { const numbers = milestone.egeNumbers as number[]; return <article key={milestone.id} className={`rounded-[24px] border p-5 ${milestone.status === "ACTIVE" ? "border-cyan-300 bg-cyan-50" : "border-slate-200 bg-white"}`}><div className="flex gap-4"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl font-black ${milestone.status === "ACTIVE" ? "bg-cyan-700 text-white" : "bg-slate-100"}`}>{index + 1}</div><div className="min-w-0"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">Неделя с {formatDate(milestone.weekStart)} · {milestone.plannedMinutes} мин.</div><h2 className="mt-1 text-xl font-black">{milestone.title}</h2><p className="mt-2 text-sm text-slate-600">{milestone.description}</p><details className="mt-3 text-sm"><summary className="cursor-pointer font-bold text-cyan-800">Почему сейчас?</summary><p className="mt-2 rounded-xl bg-white/70 p-3 leading-6 text-slate-600">{milestone.reason}</p></details>{numbers.length ? <div className="mt-4 flex flex-wrap gap-2">{numbers.map((number) => <Link key={number} href={`/student/trainer/${number}`} className="rounded-lg bg-white px-3 py-2 text-xs font-black text-cyan-800">Задание №{number}</Link>)}</div> : <Link href="/student/variants" className="mt-4 inline-flex text-sm font-black text-cyan-800">Перейти к вариантам →</Link>}</div></div></article>; })}</section></div></main>;
}
